const chronology='https://historia.tmb.cat/100-anys-metro/es/cronologia/';
export const stories=[
{id:'gran-metro',year:'1924',title:'Donde empezó todo',subtitle:'Lesseps · El primer latido',lon:2.1496,lat:41.4062,line:'L3',tag:'El origen',body:'El 30 de diciembre de 1924 abrió el Gran Metro entre Lesseps y Catalunya. Diagonal y Aragó, hoy Passeig de Gràcia, completaban las cuatro primeras estaciones. Una pequeña línea que cambiaría la escala de Barcelona.',source:chronology},
{id:'transversal',year:'1926',title:'Una ciudad de lado a lado',subtitle:'Espanya · El Transversal',lon:2.1493,lat:41.375,line:'L1',tag:'La expansión',body:'El 10 de junio de 1926 el Transversal unió la Bordeta con Catalunya. Sus nueve estaciones conectaron barrios y estaciones ferroviarias: el origen de la actual línea roja.',source:chronology},
{id:'fontana',year:'1925',title:'Gràcia entra en el mapa',subtitle:'Fontana · La estación que llegó después',lon:2.1521,lat:41.4024,line:'L3',tag:'Vida de barrio',body:'Fontana no estuvo entre las cuatro estaciones inaugurales. Abrió el 31 de mayo de 1925, entre Diagonal y Lesseps. Una parada intermedia acercó el nuevo transporte a la vida cotidiana de Gràcia.',source:chronology},
{id:'liceu',year:'1925',title:'El metro baja a la Rambla',subtitle:'Liceu · La primera prolongación',lon:2.1735,lat:41.3805,line:'L3',tag:'La ciudad cultural',body:'El 5 de julio de 1925 abrió Liceu. Fue la primera ampliación del Gran Metro, que extendió su recorrido desde Catalunya hacia la Rambla.',source:chronology},
{id:'lesseps',year:'1988',title:'Trenes que subían a la calle',subtitle:'Lesseps · Un taller sobre el túnel',lon:2.1489,lat:41.407,line:'L3',tag:'Ingeniería oculta',body:'En las cocheras de Lesseps, un elevador permitía salvar casi veinte metros entre el túnel y la superficie. El taller y la cochera se despidieron en 1988 junto al último coche de la serie 300.',source:'https://historia.tmb.cat/100-anys-metro/es/trayecto/'},
{id:'centenario',year:'2024',title:'Cien años bajo tus pies',subtitle:'Passeig de Gràcia · Memoria en el andén',lon:2.1651,lat:41.3916,line:'L3',tag:'Memoria viva',body:'Las estaciones Lesseps, Diagonal, Passeig de Gràcia y Catalunya recibieron elementos conmemorativos del centenario. Sus andenes recuerdan los nombres y la historia del primer recorrido.',source:'https://www.tmb.cat/es/centenario-metro/elementos-conmemorativos'}
];
export const tours=[{title:'El primer metro',description:'Cuatro estaciones. Un siglo de ciudad.',stops:['Lesseps','Diagonal','Passeig de Gràcia','Catalunya'],center:[2.158,41.397],zoom:13.8,bearing:25},{title:'De barrio al Mediterráneo',description:'De Gràcia a la Barceloneta, siguiendo la L4.',stops:['Joanic','Verdaguer','Urquinaona','Barceloneta'],center:[2.174,41.392],zoom:13.3,bearing:-25},{title:'Barcelona de extremo a extremo',description:'La columna vertebral roja de la metrópolis.',stops:['Hospital de Bellvitge','Espanya','Catalunya','Fondo'],center:[2.15,41.39],zoom:11.6,bearing:30}];
